# Generated by Django 3.0.5 on 2020-04-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200415_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductQuantity',
            new_name='ProductEntry',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='productEntries',
        ),
    ]
