# Generated by Django 3.0.5 on 2020-04-16 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20200415_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('street', models.CharField(max_length=20, null=True)),
                ('house_number', models.IntegerField(null=True)),
                ('apartment_number', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('productEntries', models.ManyToManyField(to='shop.ProductEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
